"""removed column from table

Revision ID: 41ca01f35189
Revises: 
Create Date: 2024-12-18 00:43:52.705783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ca01f35189'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('month', sa.Integer(), nullable=False))
    op.drop_constraint('payments_payment_id_key', 'payments', type_='unique')
    op.drop_column('payments', 'payment_metadata')
    op.drop_column('payments', 'payment_id')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.add_column('payments', sa.Column('payment_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payment_metadata', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('payments_payment_id_key', 'payments', ['payment_id'])
    op.drop_column('payments', 'month')
    # ### end Alembic commands ###
